// Speaker and Faculty Photo Registry
// Synchronized with ISOT 2026 Brochure V23-1 & Official Faculty Directory

export const SPEAKER_IMAGE_MAP: Record<string, string> = {
  'Abhijat Sheth': '/api/speaker-image/abhijat-sheth.png',
  'Adrienne Seitz': '/api/speaker-image/adrienne-seitz.png',
  'Ajay Sharma': '/api/speaker-image/ajay-sharma.png',
  'Akash Shukla': '/api/speaker-image/akash-shukla.png',
  'Allan Massie': '/api/speaker-image/allan-massie.png',
  'Amit Gupta': '/api/speaker-image/amit-gupta.png',
  'Aneesh Srivastava': '/api/speaker-image/aneesh-srivastava.png',
  'Anshuman Saha': '/api/speaker-image/anshuman-saha.png',
  'Anup Barman': '/api/speaker-image/anup-barman.png',
  'Anurag Gupta': '/api/speaker-image/anurag-gupta.png',
  'Arpita Ray Chaudhury': '/api/speaker-image/arpita-ray-chaudhury.png',
  'Ashish Shah': '/api/speaker-image/ashish-shah.png',
  'Atul Goel': '/api/speaker-image/atul-goel.png',
  'Avnish Seth': '/api/speaker-image/avnish-seth.png',
  'Awadhesh Kumar Yadav': '/api/speaker-image/awadhesh-kumar-yadav.png',
  'Debasis Das': '/api/speaker-image/debasis-das.png',
  'Deepesh Kenwar': '/api/speaker-image/deepesh-kenwar.png',
  'Dhananjai Agarwal': '/api/speaker-image/dhananjai-agrawal.png',
  'Dhananjai Agrawal': '/api/speaker-image/dhananjai-agrawal.png',
  'Dhananjaya K L': '/api/speaker-image/dhananjaya-k-l.png',
  'Dhannanjay Agarwal': '/api/speaker-image/dhananjai-agrawal.png',
  'Dilip Deshmukh': '/api/speaker-image/dilip-deshmukh.png',
  'Dolly Daniel': '/api/speaker-image/dolly-daniel.png',
  'Dr. Abhijat Sheth': '/api/speaker-image/abhijat-sheth.png',
  'Dr. Adrienne Seitz': '/api/speaker-image/adrienne-seitz.png',
  'Dr. Ajay Sharma': '/api/speaker-image/ajay-sharma.png',
  'Dr. Akash Shukla': '/api/speaker-image/akash-shukla.png',
  'Dr. Allan Massie': '/api/speaker-image/allan-massie.png',
  'Dr. Amit Gupta': '/api/speaker-image/amit-gupta.png',
  'Dr. Aneesh Srivastava': '/api/speaker-image/aneesh-srivastava.png',
  'Dr. Anshuman Saha': '/api/speaker-image/anshuman-saha.png',
  'Dr. Anup Barman': '/api/speaker-image/anup-barman.png',
  'Dr. Anurag Gupta': '/api/speaker-image/anurag-gupta.png',
  'Dr. Arpita Ray Chaudhury': '/api/speaker-image/arpita-ray-chaudhury.png',
  'Dr. Ashish Shah': '/api/speaker-image/ashish-shah.png',
  'Dr. Atul Goel': '/api/speaker-image/atul-goel.png',
  'Dr. Avnish Seth': '/api/speaker-image/avnish-seth.png',
  'Dr. Awadhesh Kumar Yadav': '/api/speaker-image/awadhesh-kumar-yadav.png',
  'Dr. Debasis Das': '/api/speaker-image/debasis-das.png',
  'Dr. Deepesh Kenwar': '/api/speaker-image/deepesh-kenwar.png',
  'Dr. Dhananjai Agarwal': '/api/speaker-image/dhananjai-agrawal.png',
  'Dr. Dhananjai Agrawal': '/api/speaker-image/dhananjai-agrawal.png',
  'Dr. Dhananjaya K L': '/api/speaker-image/dhananjaya-k-l.png',
  'Dr. Dhannanjay Agarwal': '/api/speaker-image/dhananjai-agrawal.png',
  'Dr. Dilip Deshmukh': '/api/speaker-image/dilip-deshmukh.png',
  'Dr. Dolly Daniel': '/api/speaker-image/dolly-daniel.png',
  'Dr. Edwin Fernando': '/api/speaker-image/edwin-fernando.png',
  'Dr. Feroz Aziz': '/api/speaker-image/feroz-aziz.png',
  'Dr. Geetesh MS': '/api/speaker-image/geetesh-ms.png',
  'Dr. Georgi Abraham': '/api/speaker-image/georgi-abraham.png',
  'Dr. Gireesh MS': '/api/speaker-image/geetesh-ms.png',
  'Dr. Gopala Krishna Gokhale': '/api/speaker-image/gopala-krishna-gokhale.png',
  'Dr. Gopaluni Seerapani': '/api/speaker-image/gopaluni-sirapani.png',
  'Dr. Gopaluni Sirapani': '/api/speaker-image/gopaluni-sirapani.png',
  'Dr. Hari Shankar Meshram': '/api/speaker-image/hari-shankar-meshram.png',
  'Dr. Jasmeet Kaur': '/api/speaker-image/jasmeet-kaur.png',
  'Dr. Jayesh Sachde': '/api/speaker-image/jayesh-sachde.png',
  'Dr. Jeyakumar Meyyappan': '/api/speaker-image/jeyakumar-meyyappan.png',
  'Dr. Jithu Kurian': '/api/speaker-image/jithu-kurian.png',
  'Dr. Khushboo Saxena': '/api/speaker-image/khushboo-saxena.png',
  'Dr. Kishor Wani': '/api/speaker-image/kishor-wani.png',
  'Dr. Koushik Amancharla': '/api/speaker-image/koushik-amancharla.png',
  'Dr. Krishna V Patil': '/api/speaker-image/krishna-v-patil.png',
  'Dr. Mahesh V': '/api/speaker-image/mahesh-vankalakunti.png',
  'Dr. Mahesh Vankalakunti': '/api/speaker-image/mahesh-vankalakunti.png',
  'Dr. Mahesha V': '/api/speaker-image/mahesh-vankalakunti.png',
  'Dr. Mamidi Neeraja': '/api/speaker-image/mamidi-neeraja.png',
  'Dr. Manish Balwani': '/api/speaker-image/manish-balwani.png',
  'Dr. Manish Jain': '/api/speaker-image/manish-jain.png',
  'Dr. Manish R Balwani': '/api/speaker-image/manish-balwani.png',
  'Dr. Manish Shrigiriwa': '/api/speaker-image/manish-singhshikha.png',
  'Dr. Manish Singhshikha': '/api/speaker-image/manish-singhshikha.png',
  'Dr. Marcello Cantarovich': '/api/speaker-image/marcello-cantarovich.png',
  'Dr. Maria Paula Gomez': '/api/speaker-image/maria-paula-gomez.png',
  'Dr. Mehul Shah': '/api/speaker-image/mehul-shah.png',
  'Dr. Mohamed Rela': '/api/speaker-image/mohamed-rela.png',
  'Dr. N Gopalakrishnan': '/api/speaker-image/natarajan-gopalakrishnan.png',
  'Dr. Narayan Prasad': '/api/speaker-image/narayan-prasad.png',
  'Dr. Natarajan Gopalakrishnan': '/api/speaker-image/natarajan-gopalakrishnan.png',
  'Dr. Neelam Mohan': '/api/speaker-image/neelam-mohan.png',
  'Dr. Nilesh Mandlewal': '/api/speaker-image/nilesh-mandlewal.png',
  'Dr. Pranab Modi': '/api/speaker-image/pranab-modi.png',
  'Dr. Pranav Modi': '/api/speaker-image/pranab-modi.png',
  'Dr. Pratik Das': '/api/speaker-image/pratik-das.png',
  'Dr. RP Mathur': '/api/speaker-image/rp-mathur.png',
  'Dr. Radhika Krishna Patil': '/api/speaker-image/krishna-v-patil.png',
  'Dr. Rahul Pandit': '/api/speaker-image/rahul-pandit.png',
  'Dr. Raj Kanwar Yadav': '/api/speaker-image/raj-kumar-yadav.png',
  'Dr. Raj Kumar Yadav': '/api/speaker-image/raj-kumar-yadav.png',
  'Dr. Rajani M': '/api/speaker-image/rajani-m.png',
  'Dr. Rakesh Joshi': '/api/speaker-image/rakesh-joshi.png',
  'Dr. Ravi Mohanka': '/api/speaker-image/ravi-mohanka.png',
  'Dr. Ritu Agarwal': '/api/speaker-image/ritu-agarwal.png',
  'Dr. Rushi Deshpande': '/api/speaker-image/rushi-deshpande.png',
  'Dr. S Sakthi Selva Kumar': '/api/speaker-image/s-sakthi-selva-kumar.png',
  'Dr. Sakthi Selvakumar': '/api/speaker-image/s-sakthi-selva-kumar.png',
  'Dr. Sandeep Attawar': '/api/speaker-image/sandeep-attawar.png',
  'Dr. Sanjay Kolte': '/api/speaker-image/sanjay-kolte.png',
  'Dr. Sanjay Kumar Agarwal': '/api/speaker-image/sanjay-kumar-agarwal.png',
  'Dr. Sanjay Nagral': '/api/speaker-image/sanjay-nagral.png',
  'Dr. Santosh Varughese': '/api/speaker-image/santosh-varughese.png',
  'Dr. Sarbpreet Singh': '/api/speaker-image/sarbpreet-singh.png',
  'Dr. Shalini Garg': '/api/speaker-image/shalini-garg.png',
  'Dr. Sharadalekha Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Dr. Shiny Pradhan': '/api/speaker-image/shiny-suman-pradhan.png',
  'Dr. Shiny Suman Pradhan': '/api/speaker-image/shiny-suman-pradhan.png',
  'Dr. Sidharth Sethi': '/api/speaker-image/sidharth-sethi.png',
  'Dr. Sourabh Sharma': '/api/speaker-image/sourabh-sharma.png',
  'Dr. Sree Bhushan Raju': '/api/speaker-image/sree-bhushan-raju.png',
  'Dr. Subramania Iyer': '/api/speaker-image/subramania-iyer.png',
  'Dr. Sukanto Das': '/api/speaker-image/sukanto-kishore-das.png',
  'Dr. Sukanto Kishore Das': '/api/speaker-image/sukanto-kishore-das.png',
  'Dr. Sunil Shroff': '/api/speaker-image/sunil-shroff.png',
  'Dr. Sunil Vasudevan': '/api/speaker-image/sunil-vasudevan.png',
  'Dr. Swarnalata Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Dr. Swarnalatha Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Dr. Umapati Hegde': '/api/speaker-image/umapati-hegde.png',
  'Dr. V.K. Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Dr. VK Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Dr. Vatsala Trivedi': '/api/speaker-image/vatsala-trivedi.png',
  'Dr. Vinant Bhargava': '/api/speaker-image/vinant-bhargava.png',
  'Dr. Vinod Kumar Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Dr. Vivek Kute': '/api/speaker-image/vivek-kute.png',
  'Dr. Yogaram Jabble': '/api/speaker-image/yogaram-jabble.png',
  'Edwin Fernando': '/api/speaker-image/edwin-fernando.png',
  'Feroz Aziz': '/api/speaker-image/feroz-aziz.png',
  'Geetesh MS': '/api/speaker-image/geetesh-ms.png',
  'Georgi Abraham': '/api/speaker-image/georgi-abraham.png',
  'Gireesh MS': '/api/speaker-image/geetesh-ms.png',
  'Gopala Krishna Gokhale': '/api/speaker-image/gopala-krishna-gokhale.png',
  'Gopaluni Seerapani': '/api/speaker-image/gopaluni-sirapani.png',
  'Gopaluni Sirapani': '/api/speaker-image/gopaluni-sirapani.png',
  'Hari Shankar Meshram': '/api/speaker-image/hari-shankar-meshram.png',
  'Jasmeet Kaur': '/api/speaker-image/jasmeet-kaur.png',
  'Jayesh Sachde': '/api/speaker-image/jayesh-sachde.png',
  'Jeyakumar Meyyappan': '/api/speaker-image/jeyakumar-meyyappan.png',
  'Jithu Kurian': '/api/speaker-image/jithu-kurian.png',
  'Khushboo Saxena': '/api/speaker-image/khushboo-saxena.png',
  'Kishor Wani': '/api/speaker-image/kishor-wani.png',
  'Koushik Amancharla': '/api/speaker-image/koushik-amancharla.png',
  'Krishna V Patil': '/api/speaker-image/krishna-v-patil.png',
  'Mahesh V': '/api/speaker-image/mahesh-vankalakunti.png',
  'Mahesh Vankalakunti': '/api/speaker-image/mahesh-vankalakunti.png',
  'Mahesha V': '/api/speaker-image/mahesh-vankalakunti.png',
  'Mamidi Neeraja': '/api/speaker-image/mamidi-neeraja.png',
  'Manish Balwani': '/api/speaker-image/manish-balwani.png',
  'Manish Jain': '/api/speaker-image/manish-jain.png',
  'Manish R Balwani': '/api/speaker-image/manish-balwani.png',
  'Manish Shrigiriwa': '/api/speaker-image/manish-singhshikha.png',
  'Manish Singhshikha': '/api/speaker-image/manish-singhshikha.png',
  'Marcello Cantarovich': '/api/speaker-image/marcello-cantarovich.png',
  'Maria Paula Gomez': '/api/speaker-image/maria-paula-gomez.png',
  'Mehul Shah': '/api/speaker-image/mehul-shah.png',
  'Mohamed Rela': '/api/speaker-image/mohamed-rela.png',
  'N Gopalakrishnan': '/api/speaker-image/natarajan-gopalakrishnan.png',
  'Narayan Prasad': '/api/speaker-image/narayan-prasad.png',
  'Natarajan Gopalakrishnan': '/api/speaker-image/natarajan-gopalakrishnan.png',
  'Neelam Mohan': '/api/speaker-image/neelam-mohan.png',
  'Nilesh Mandlewal': '/api/speaker-image/nilesh-mandlewal.png',
  'Pranab Modi': '/api/speaker-image/pranab-modi.png',
  'Pranav Modi': '/api/speaker-image/pranab-modi.png',
  'Pratik Das': '/api/speaker-image/pratik-das.png',
  'Prof. Abhijat Sheth': '/api/speaker-image/abhijat-sheth.png',
  'Prof. Adrienne Seitz': '/api/speaker-image/adrienne-seitz.png',
  'Prof. Ajay Sharma': '/api/speaker-image/ajay-sharma.png',
  'Prof. Akash Shukla': '/api/speaker-image/akash-shukla.png',
  'Prof. Allan Massie': '/api/speaker-image/allan-massie.png',
  'Prof. Amit Gupta': '/api/speaker-image/amit-gupta.png',
  'Prof. Aneesh Srivastava': '/api/speaker-image/aneesh-srivastava.png',
  'Prof. Anshuman Saha': '/api/speaker-image/anshuman-saha.png',
  'Prof. Anup Barman': '/api/speaker-image/anup-barman.png',
  'Prof. Anurag Gupta': '/api/speaker-image/anurag-gupta.png',
  'Prof. Arpita Ray Chaudhury': '/api/speaker-image/arpita-ray-chaudhury.png',
  'Prof. Ashish Shah': '/api/speaker-image/ashish-shah.png',
  'Prof. Atul Goel': '/api/speaker-image/atul-goel.png',
  'Prof. Avnish Seth': '/api/speaker-image/avnish-seth.png',
  'Prof. Awadhesh Kumar Yadav': '/api/speaker-image/awadhesh-kumar-yadav.png',
  'Prof. Debasis Das': '/api/speaker-image/debasis-das.png',
  'Prof. Deepesh Kenwar': '/api/speaker-image/deepesh-kenwar.png',
  'Prof. Dhananjai Agarwal': '/api/speaker-image/dhananjai-agrawal.png',
  'Prof. Dhananjai Agrawal': '/api/speaker-image/dhananjai-agrawal.png',
  'Prof. Dhananjaya K L': '/api/speaker-image/dhananjaya-k-l.png',
  'Prof. Dhannanjay Agarwal': '/api/speaker-image/dhananjai-agrawal.png',
  'Prof. Dilip Deshmukh': '/api/speaker-image/dilip-deshmukh.png',
  'Prof. Dolly Daniel': '/api/speaker-image/dolly-daniel.png',
  'Prof. Edwin Fernando': '/api/speaker-image/edwin-fernando.png',
  'Prof. Feroz Aziz': '/api/speaker-image/feroz-aziz.png',
  'Prof. Geetesh MS': '/api/speaker-image/geetesh-ms.png',
  'Prof. Georgi Abraham': '/api/speaker-image/georgi-abraham.png',
  'Prof. Gireesh MS': '/api/speaker-image/geetesh-ms.png',
  'Prof. Gopala Krishna Gokhale': '/api/speaker-image/gopala-krishna-gokhale.png',
  'Prof. Gopaluni Seerapani': '/api/speaker-image/gopaluni-sirapani.png',
  'Prof. Gopaluni Sirapani': '/api/speaker-image/gopaluni-sirapani.png',
  'Prof. Hari Shankar Meshram': '/api/speaker-image/hari-shankar-meshram.png',
  'Prof. Jasmeet Kaur': '/api/speaker-image/jasmeet-kaur.png',
  'Prof. Jayesh Sachde': '/api/speaker-image/jayesh-sachde.png',
  'Prof. Jeyakumar Meyyappan': '/api/speaker-image/jeyakumar-meyyappan.png',
  'Prof. Jithu Kurian': '/api/speaker-image/jithu-kurian.png',
  'Prof. Khushboo Saxena': '/api/speaker-image/khushboo-saxena.png',
  'Prof. Kishor Wani': '/api/speaker-image/kishor-wani.png',
  'Prof. Koushik Amancharla': '/api/speaker-image/koushik-amancharla.png',
  'Prof. Krishna V Patil': '/api/speaker-image/krishna-v-patil.png',
  'Prof. Mahesh V': '/api/speaker-image/mahesh-vankalakunti.png',
  'Prof. Mahesh Vankalakunti': '/api/speaker-image/mahesh-vankalakunti.png',
  'Prof. Mahesha V': '/api/speaker-image/mahesh-vankalakunti.png',
  'Prof. Mamidi Neeraja': '/api/speaker-image/mamidi-neeraja.png',
  'Prof. Manish Balwani': '/api/speaker-image/manish-balwani.png',
  'Prof. Manish Jain': '/api/speaker-image/manish-jain.png',
  'Prof. Manish R Balwani': '/api/speaker-image/manish-balwani.png',
  'Prof. Manish Shrigiriwa': '/api/speaker-image/manish-singhshikha.png',
  'Prof. Manish Singhshikha': '/api/speaker-image/manish-singhshikha.png',
  'Prof. Marcello Cantarovich': '/api/speaker-image/marcello-cantarovich.png',
  'Prof. Maria Paula Gomez': '/api/speaker-image/maria-paula-gomez.png',
  'Prof. Mehul Shah': '/api/speaker-image/mehul-shah.png',
  'Prof. Mohamed Rela': '/api/speaker-image/mohamed-rela.png',
  'Prof. N Gopalakrishnan': '/api/speaker-image/natarajan-gopalakrishnan.png',
  'Prof. Narayan Prasad': '/api/speaker-image/narayan-prasad.png',
  'Prof. Natarajan Gopalakrishnan': '/api/speaker-image/natarajan-gopalakrishnan.png',
  'Prof. Neelam Mohan': '/api/speaker-image/neelam-mohan.png',
  'Prof. Nilesh Mandlewal': '/api/speaker-image/nilesh-mandlewal.png',
  'Prof. Pranab Modi': '/api/speaker-image/pranab-modi.png',
  'Prof. Pranav Modi': '/api/speaker-image/pranab-modi.png',
  'Prof. Pratik Das': '/api/speaker-image/pratik-das.png',
  'Prof. RP Mathur': '/api/speaker-image/rp-mathur.png',
  'Prof. Radhika Krishna Patil': '/api/speaker-image/krishna-v-patil.png',
  'Prof. Rahul Pandit': '/api/speaker-image/rahul-pandit.png',
  'Prof. Raj Kanwar Yadav': '/api/speaker-image/raj-kumar-yadav.png',
  'Prof. Raj Kumar Yadav': '/api/speaker-image/raj-kumar-yadav.png',
  'Prof. Rajani M': '/api/speaker-image/rajani-m.png',
  'Prof. Rakesh Joshi': '/api/speaker-image/rakesh-joshi.png',
  'Prof. Ravi Mohanka': '/api/speaker-image/ravi-mohanka.png',
  'Prof. Ritu Agarwal': '/api/speaker-image/ritu-agarwal.png',
  'Prof. Rushi Deshpande': '/api/speaker-image/rushi-deshpande.png',
  'Prof. S Sakthi Selva Kumar': '/api/speaker-image/s-sakthi-selva-kumar.png',
  'Prof. Sakthi Selvakumar': '/api/speaker-image/s-sakthi-selva-kumar.png',
  'Prof. Sandeep Attawar': '/api/speaker-image/sandeep-attawar.png',
  'Prof. Sanjay Kolte': '/api/speaker-image/sanjay-kolte.png',
  'Prof. Sanjay Kumar Agarwal': '/api/speaker-image/sanjay-kumar-agarwal.png',
  'Prof. Sanjay Nagral': '/api/speaker-image/sanjay-nagral.png',
  'Prof. Santosh Varughese': '/api/speaker-image/santosh-varughese.png',
  'Prof. Sarbpreet Singh': '/api/speaker-image/sarbpreet-singh.png',
  'Prof. Shalini Garg': '/api/speaker-image/shalini-garg.png',
  'Prof. Sharadalekha Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Prof. Shiny Pradhan': '/api/speaker-image/shiny-suman-pradhan.png',
  'Prof. Shiny Suman Pradhan': '/api/speaker-image/shiny-suman-pradhan.png',
  'Prof. Sidharth Sethi': '/api/speaker-image/sidharth-sethi.png',
  'Prof. Sourabh Sharma': '/api/speaker-image/sourabh-sharma.png',
  'Prof. Sree Bhushan Raju': '/api/speaker-image/sree-bhushan-raju.png',
  'Prof. Subramania Iyer': '/api/speaker-image/subramania-iyer.png',
  'Prof. Sukanto Das': '/api/speaker-image/sukanto-kishore-das.png',
  'Prof. Sukanto Kishore Das': '/api/speaker-image/sukanto-kishore-das.png',
  'Prof. Sunil Shroff': '/api/speaker-image/sunil-shroff.png',
  'Prof. Sunil Vasudevan': '/api/speaker-image/sunil-vasudevan.png',
  'Prof. Swarnalata Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Prof. Swarnalatha Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Prof. Umapati Hegde': '/api/speaker-image/umapati-hegde.png',
  'Prof. V.K. Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Prof. VK Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Prof. Vatsala Trivedi': '/api/speaker-image/vatsala-trivedi.png',
  'Prof. Vinant Bhargava': '/api/speaker-image/vinant-bhargava.png',
  'Prof. Vinod Kumar Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Prof. Vivek Kute': '/api/speaker-image/vivek-kute.png',
  'Prof. Yogaram Jabble': '/api/speaker-image/yogaram-jabble.png',
  'RP Mathur': '/api/speaker-image/rp-mathur.png',
  'Radhika Krishna Patil': '/api/speaker-image/krishna-v-patil.png',
  'Rahul Pandit': '/api/speaker-image/rahul-pandit.png',
  'Raj Kanwar Yadav': '/api/speaker-image/raj-kumar-yadav.png',
  'Raj Kumar Yadav': '/api/speaker-image/raj-kumar-yadav.png',
  'Rajani M': '/api/speaker-image/rajani-m.png',
  'Rakesh Joshi': '/api/speaker-image/rakesh-joshi.png',
  'Ravi Mohanka': '/api/speaker-image/ravi-mohanka.png',
  'Ritu Agarwal': '/api/speaker-image/ritu-agarwal.png',
  'Rushi Deshpande': '/api/speaker-image/rushi-deshpande.png',
  'S Sakthi Selva Kumar': '/api/speaker-image/s-sakthi-selva-kumar.png',
  'Sakthi Selvakumar': '/api/speaker-image/s-sakthi-selva-kumar.png',
  'Sandeep Attawar': '/api/speaker-image/sandeep-attawar.png',
  'Sanjay Kolte': '/api/speaker-image/sanjay-kolte.png',
  'Sanjay Kumar Agarwal': '/api/speaker-image/sanjay-kumar-agarwal.png',
  'Sanjay Nagral': '/api/speaker-image/sanjay-nagral.png',
  'Santosh Varughese': '/api/speaker-image/santosh-varughese.png',
  'Sarbpreet Singh': '/api/speaker-image/sarbpreet-singh.png',
  'Shalini Garg': '/api/speaker-image/shalini-garg.png',
  'Sharadalekha Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Shiny Pradhan': '/api/speaker-image/shiny-suman-pradhan.png',
  'Shiny Suman Pradhan': '/api/speaker-image/shiny-suman-pradhan.png',
  'Sidharth Sethi': '/api/speaker-image/sidharth-sethi.png',
  'Sourabh Sharma': '/api/speaker-image/sourabh-sharma.png',
  'Sree Bhushan Raju': '/api/speaker-image/sree-bhushan-raju.png',
  'Sreebhushan Raju': '/api/speaker-image/sree-bhushan-raju.png',
  'Dr Sreebhushan Raju': '/api/speaker-image/sree-bhushan-raju.png',
  'Dr. Sreebhushan Raju': '/api/speaker-image/sree-bhushan-raju.png',
  'Subramania Iyer': '/api/speaker-image/subramania-iyer.png',
  'Sukanto Das': '/api/speaker-image/sukanto-kishore-das.png',
  'Sukanto Kishore Das': '/api/speaker-image/sukanto-kishore-das.png',
  'Sunil Shroff': '/api/speaker-image/sunil-shroff.png',
  'Sunil Vasudevan': '/api/speaker-image/sunil-vasudevan.png',
  'Swarnalata Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Swarnalatha Guditi': '/api/speaker-image/sharadalekha-guditi.png',
  'Umapati Hegde': '/api/speaker-image/umapati-hegde.png',
  'V.K. Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'VK Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Vatsala Trivedi': '/api/speaker-image/vatsala-trivedi.png',
  'Vinant Bhargava': '/api/speaker-image/vinant-bhargava.png',
  'Vinod Kumar Paul': '/api/speaker-image/vinod-kumar-paul.png',
  'Vivek Kute': '/api/speaker-image/vivek-kute.png',
  'Yogaram Jabble': '/api/speaker-image/yogaram-jabble.png',
};

/**
 * Normalizes a speaker name for lookup in the photo map
 */
export function normalizeSpeakerName(name: string): string {
  if (!name) return '';
  return name
    .trim()
    .replace(/^(Dr\.?|Prof\.?|Padma Shri|Padmashri|Padma Bhushan)\s+/i, '')
    .replace(/\s+/g, ' ')
    .trim();
}

/**
 * Returns the photo URL for a speaker name if available.
 * Checks dynamic uploaded photos first, then static registry.
 */
export function getSpeakerPhoto(
  name: string,
  dynamicPhotos?: Record<string, string>
): string | null {
  if (!name) return null;
  const trimmed = name.trim();
  const normalized = normalizeSpeakerName(trimmed);

  // 1. Dynamic uploaded photos from R2 / D1
  if (dynamicPhotos) {
    const slug = normalized.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    if (dynamicPhotos[slug]) return dynamicPhotos[slug];
    if (dynamicPhotos[trimmed]) return dynamicPhotos[trimmed];
    if (dynamicPhotos[normalized]) return dynamicPhotos[normalized];
  }

  // 2. Exact match in static map
  if (SPEAKER_IMAGE_MAP[trimmed]) {
    return SPEAKER_IMAGE_MAP[trimmed];
  }

  // 3. Normalized match
  if (SPEAKER_IMAGE_MAP[normalized]) {
    return SPEAKER_IMAGE_MAP[normalized];
  }

  // 4. Case-insensitive lookup
  const lowerTrimmed = trimmed.toLowerCase();
  const lowerNormalized = normalized.toLowerCase();
  for (const [key, val] of Object.entries(SPEAKER_IMAGE_MAP)) {
    const kLower = key.toLowerCase();
    if (kLower === lowerTrimmed || kLower === lowerNormalized) {
      return val;
    }
  }

  return null;
}
